stages:
    - build
    - test

build-cmake:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make $CMAKEBUILD
    only:
        - master

build-automake:
    stage: build
    script:
        - ./bootstrap
        - ./configure
        - make
    only:
        - master

build-automake-cuda:
    stage: build
    script:
        - ./bootstrap
        - ./configure --enable-cuda
        - make
    only:
        - master

test-cmake:
    stage: test
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make check-all
    only:
        - master

test-automake:
    stage: test
    script:
        - ./bootstrap
        - ./configure --disable-debug
        - make
        - make check
    only:
        - master

test-automake-cuda:
    stage: test
    script:
        - ./bootstrap
        - ./configure --enable-cuda --disable-debug
        - make
        - make check
    only:
        - master

